<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MSI" failures="5" tests="5" name="testRunner.RunnerClass" time="8.435" errors="0" timestamp="2024-08-26T16:47:31 IST" skipped="0">
  <testcase classname="testRunner.RunnerClass" name="runScenario" time="2.964">
    <failure message="The following asserts failed:
	expected [200] but found [429]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [429]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at stepDefinitionFiles.MyStepDefinition.user_hits_the_get_agify_api_service_and_acquire_all_the_required_user_details_by_passing_as_the_query_parameter(MyStepDefinition.java:35)
at ✽.User hits the get AGIFY API service and acquire all the required user details by passing "john" as the query parameter(file:///C:/Users/Shanmugam%20Rani/eclipse-workspace/Altimetrik.MiniProjects.APIAutomation/src/test/java/cucumberFeatureFiles/AgifyAPITestCases.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testRunner.RunnerClass" name="runScenario" time="1.268">
    <failure message="The following asserts failed:
	expected [200] but found [429]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [429]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at stepDefinitionFiles.MyStepDefinition.user_hits_the_get_agify_api_service_and_acquire_all_the_required_user_details_by_passing_as_the_query_parameter(MyStepDefinition.java:35)
at ✽.User hits the get AGIFY API service and acquire all the required user details by passing "jerry" as the query parameter(file:///C:/Users/Shanmugam%20Rani/eclipse-workspace/Altimetrik.MiniProjects.APIAutomation/src/test/java/cucumberFeatureFiles/AgifyAPITestCases.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testRunner.RunnerClass" name="runScenario" time="1.436">
    <failure message="The following asserts failed:
	expected [200] but found [429]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [429]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at stepDefinitionFiles.MyStepDefinition.user_hits_the_get_agify_api_service_and_acquire_all_the_required_user_details_by_passing_as_the_query_parameter(MyStepDefinition.java:35)
at ✽.User hits the get AGIFY API service and acquire all the required user details by passing "kevin" as the query parameter(file:///C:/Users/Shanmugam%20Rani/eclipse-workspace/Altimetrik.MiniProjects.APIAutomation/src/test/java/cucumberFeatureFiles/AgifyAPITestCases.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testRunner.RunnerClass" name="runScenario" time="1.364">
    <failure message="The following asserts failed:
	expected [200] but found [429]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [429]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at stepDefinitionFiles.MyStepDefinition.user_hits_the_get_agify_api_service_and_acquire_all_the_required_user_details_by_passing_as_the_query_parameter(MyStepDefinition.java:35)
at ✽.User hits the get AGIFY API service and acquire all the required user details by passing "tom" as the query parameter(file:///C:/Users/Shanmugam%20Rani/eclipse-workspace/Altimetrik.MiniProjects.APIAutomation/src/test/java/cucumberFeatureFiles/AgifyAPITestCases.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testRunner.RunnerClass" name="runScenario" time="1.403">
    <failure message="The following asserts failed:
	expected [200] but found [429]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [429]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at stepDefinitionFiles.MyStepDefinition.user_hits_the_get_agify_api_service_and_acquire_all_the_required_user_details_by_passing_as_the_query_parameter(MyStepDefinition.java:35)
at ✽.User hits the get AGIFY API service and acquire all the required user details by passing "amanda" as the query parameter(file:///C:/Users/Shanmugam%20Rani/eclipse-workspace/Altimetrik.MiniProjects.APIAutomation/src/test/java/cucumberFeatureFiles/AgifyAPITestCases.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- testRunner.RunnerClass -->
